services:
  # === FRONTEND (React + Vite) ===
  - type: static
    name: ortho-vaidya-chat-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        # Your live backend URL
        value: "https://orthovaidhya.onrender.com"

  # === BACKEND (Flask API) ===
  - type: web
    name: ortho-vaidya-chat-backend
    runtime: python
    buildCommand: cd backend && python -m pip install -r requirements.txt
    startCommand: cd backend && gunicorn --workers 2 --bind 0.0.0.0:$PORT web_api:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FRONTEND_URL
        # Your live frontend URL
        value: "https://vaidhya-6t0w.onrender.com"
