services:
  # === FRONTEND (React + Vite) ===
  - type: static
    name: ortho-vaidya-chat-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://ortho-vaidya-chat-backend.onrender.com

  # === BACKEND (Flask API) ===
  - type: web
    name: ortho-vaidya-chat-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT web_api:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: "3.11"