version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - GEMINI_API_KEY=your_api_key_here
    volumes:
      - .:/app
    restart: unless-stopped